name: GitHub-Profile-3D-Contrib

on:
  schedule: # Runs at 00:00 every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4 # <-- Updated to v4 to fix the warning
      - uses: yoshi389111/github-profile-3d-contrib@0.8.0 # <-- Updated to latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated 3D contribution city" || echo "No changes to commit"
          git push
